package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class startScreen extends JFrame {
    public static String url;
    public static String user;
    public static String password;
    public static String driver;
    private JButton searchStoresButton;
    private JPanel startPanel;
    private JButton showAllStoresButton;
    private JButton searchItemsButton;
    private JButton showAllItemsButton;
    private JButton searchCategoriesButton;
    private JButton showAllCategoriesButton;
    private JLabel startPanelLabel;
    private JTextField urlField;
    private JTextField usernameField;
    private JTextField passwordField;
    private JLabel urlLabel;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JLabel driverLabel;
    private JTextField driverField;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public startScreen() {
        add(startPanel);

        setTitle("Where's That Foam Roller?");
        setSize(400, 500);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        searchStoresButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                searchStores searchStores = new searchStores();
                //dispose();
                searchStores.setVisible(true);
            }
        });
        showAllStoresButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                showAllStores showAllStores = new showAllStores();
                //dispose();
                showAllStores.setVisible(true);
            }
        });
        searchItemsButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                searchItems searchItems = new searchItems();
                //dispose();
                searchItems.setVisible(true);
            }
        });
        showAllItemsButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                showAllItems showAllItems = new showAllItems();
                //dispose();
                showAllItems.setVisible(true);
            }
        });
        searchCategoriesButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                searchCategories searchCategories = new searchCategories();
                //dispose();
                searchCategories.setVisible(true);
            }
        });
        showAllCategoriesButton.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent e) {
                setConnectionParameters();
                showAllCategories showAllCategories = new showAllCategories();
                //dispose();
                showAllCategories.setVisible(true);
            }
        });
    }

    public void setConnectionParameters() {
        url = urlField.getText().trim();
        user = usernameField.getText().trim();
        password = passwordField.getText().trim();
        driver = driverField.getText().trim();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        startPanel = new JPanel();
        startPanel.setLayout(
            new com.intellij.uiDesigner.core.GridLayoutManager(10, 2, new Insets(0, 0, 0, 0), -1,
                -1));
        showAllItemsButton = new JButton();
        showAllItemsButton.setText("Show All Items");
        startPanel.add(showAllItemsButton,
            new com.intellij.uiDesigner.core.GridConstraints(8, 1, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        searchItemsButton = new JButton();
        searchItemsButton.setHorizontalTextPosition(0);
        searchItemsButton.setText("Search Items");
        startPanel.add(searchItemsButton,
            new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        searchStoresButton = new JButton();
        searchStoresButton.setText("Search Stores");
        startPanel.add(searchStoresButton,
            new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        showAllStoresButton = new JButton();
        showAllStoresButton.setText("Show All Stores");
        startPanel.add(showAllStoresButton,
            new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        showAllCategoriesButton = new JButton();
        showAllCategoriesButton.setText("Show All Categories");
        startPanel.add(showAllCategoriesButton,
            new com.intellij.uiDesigner.core.GridConstraints(9, 1, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        searchCategoriesButton = new JButton();
        searchCategoriesButton.setText("Search Categories");
        startPanel.add(searchCategoriesButton,
            new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
                new Dimension(125, 50), null, 0, false));
        startPanelLabel = new JLabel();
        Font startPanelLabelFont =
            this.$$$getFont$$$(null, Font.BOLD, 12, startPanelLabel.getFont());
        if (startPanelLabelFont != null)
            startPanelLabel.setFont(startPanelLabelFont);
        startPanelLabel.setText("Choose Search Method:");
        startPanel.add(startPanelLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
            com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2,
            false));
        urlLabel = new JLabel();
        urlLabel.setText("SQL URL");
        startPanel.add(urlLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
            com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
        urlField = new JTextField();
        startPanel.add(urlField, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
            new Dimension(150, -1), null, 0, false));
        usernameLabel = new JLabel();
        usernameLabel.setText("SQL Username");
        startPanel.add(usernameLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
            com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
        passwordLabel = new JLabel();
        passwordLabel.setText("SQL Password");
        startPanel.add(passwordLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
            com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
        usernameField = new JTextField();
        startPanel.add(usernameField, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
            new Dimension(150, -1), null, 0, false));
        passwordField = new JTextField();
        startPanel.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
            new Dimension(150, -1), null, 0, false));
        driverLabel = new JLabel();
        driverLabel.setText("SQL Driver");
        startPanel.add(driverLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
            com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
        driverField = new JTextField();
        startPanel.add(driverField, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 2,
            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null,
            new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null)
            return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
            size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return startPanel;
    }
}
